---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - agentrax.io
  resources:
  - agentdeployments
  - tenantquotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentrax.io
  resources:
  - agentdeployments/finalizers
  - tenantquotas/finalizers
  verbs:
  - update
- apiGroups:
  - agentrax.io
  resources:
  - agentdeployments/status
  - tenantquotas/status
  verbs:
  - get
  - patch
  - update
