{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentrax.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentrax.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.workloadIdentity.enabled (eq .Values.workloadIdentity.provider "azure") }}
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.azureClientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.workloadIdentity.azureTenantId | quote }}
    {{- end }}
    {{- if and .Values.workloadIdentity.enabled (eq .Values.workloadIdentity.provider "aws") }}
    eks.amazonaws.com/role-arn: {{ .Values.workloadIdentity.awsRoleArn | quote }}
    {{- end }}
{{- end }}
